settings:
  search: ontap-systems
  name: "ONTAP Systems"
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: AFF and FAS system docs
      url: "/index.html"
    - title: Get started
      entries:
        - title: What's new
          url: /whats-new.html
        - title: Release notes
          url: /rel-notes.html
    - title: AFF systems
      entries:
      - section: c190
      - section: a200
      - title: AFF A220 systems
        entries:
          - title: Install and setup
            pdf-filename: AFF A220 and FAS2700 Install and Setup
            entries:
            - title: Choose install and setup experience
              url: /fas2700/install-setup.html
            - title: Quick steps
              url: /fas2700/install-quick-guide.html
            - title: Videos steps
              url: /fas2700/install-videos.html
            - title: Detailed steps
              url: /fas2700/install-detailed-guide.html
          - title: Maintain
            pdf-filename: AFF A220 and FAS2700 Maintain
            entries:
            - title: Boot media
              pdf-filename: AFF A220 and FAS2700 Boot Media
              entries:
                - title: Overview
                  url: /fas2700/bootmedia-replace-overview.html
                - title: Check onboard encryption keys
                  url: /fas2700/bootmedia-encryption-preshutdown-checks.html
                - title: Shut down impaired controller
                  url: /fas2700/bootmedia-impaired-controller-shutdown.html
                - title: Replace boot image
                  url: /fas2700/bootmedia-replace.html
                - title: Boot recovery image
                  url: /fas2700/bootmedia-recovery-image-boot-non-2n-mcc.html
                - title: Restore OKM, NSE, and NVE
                  url: /fas2700/bootmedia-encryption-restore.html
                - title: Return failed part to NetApp
                  url: /fas2700/bootmedia-complete-rma.html
            - title: Caching module
              pdf-filename: AFF A220 and FAS2700 Caching Module
              url: /fas2700/caching-module-replace.html
            - title: Chassis
              pdf-filename: AFF A220 and FAS2700 Chassis
              entries:
                - title: Overview
                  url: /fas2700/chassis-replace-overview.html
                - title: Shut down impaired controller
                  url: /fas2700/chassis-replace-shutdown.html
                - title: Replace hardware
                  url: /fas2700/chassis-replace-move-hardware.html
                - title: Restore configuration
                  url: /fas2700/chassis-replace-complete-system-restore-rma.html
            - title: Controller
              pdf-filename: AFF A220 and FAS2700 Controller
              entries:
                - title: Overview
                  url: /fas2700/controller-replace-overview.html
                - title: Shut down impaired controller
                  url: /fas2700/controller-replace-shutdown.html
                - title: Replace controller hardware
                  url: /fas2700/controller-replace-move-hardware.html
                - title: Restore system configuration
                  url: /fas2700/controller-replace-system-config-restore-and-verify.html
                - title: Recable system
                  url: /fas2700/controller-replace-recable-reassign-disks.html
                - title: Complete system restoration
                  url: /fas2700/controller-replace-restore-system-rma.html
            - title: DIMM
              pdf-filename: AFF A220 and FAS2700 DIMM
              url: /fas2700/dimm-replace.html
            - title: NVMEM battery
              pdf-filename: AFF A220 and FAS2700 NVMEM Battery
              url: /fas2700/nvmem-nvram-battery-replace.html
            - title: Power supply
              pdf-filename: AFF A220 and FAS2700 Power Supply
              url: /fas2700/power-supply-swap-out.html
            - title: Real-time clock battery
              pdf-filename: AFF A220 and FAS2700 Real-Time Clock Battery
              url: /fas2700/rtc-battery-replace.html
      - section: a250
      - section: a300
      - section: a320
      - section: a400
      - section: a700s
      - section: a800
      - section: a900
    - title: FAS systems
      entries:
      - section: fas500f
      - section: fas2600
      - section: fas8200
      - section: fas8300
      - section: fas9500
    - title: AFF and FAS systems
      entries:
        - section: fas2700
        - section: fas9000
    - title: System-level diagnostics
      entries:
        - title: Introduction
          url: /platform-supplemental/sldiag-introduction.html
        - title: Requirements
          url: /platform-supplemental/sldiag-requirements.html
        - title: How to use command-line help
          url: /platform-supplemental/sldiag-use-cli-help.html
        - title: Run system install diagnostics
          url: /platform-supplemental/sldiag-system-installation-diagnostics.html
        - title: Run system panic diagnostics
          url: /platform-supplemental/sldiag-system-panic-diagnostics.html
        - title: Run slow system response diagnostics
          url: /platform-supplemental/sldiag-slow-system-diagnostics.html
        - title: Run hardware install diagnostics
          url: /platform-supplemental/sldiag-hardware-installation-diagnostics.html
        - title: Run device failure diagnostics
          url: /platform-supplemental/sldiag-device-failure-diagnostics.html
    - title: Drive shelves and disk drives
      entries:
        - section: ns224
        - section: sas3
        - title: Hot swap internal disk drive
          entries:
          - title: Video overview
            url: /platform-supplemental/drive-video.html
          - title: Which procedure to use
            url: /platform-supplemental/drive-hotswap.html
          - title: Hot-swap SSD
            url: /platform-supplemental/drive-hotswap-drive.html
          - title: Hot-swap HDD
            url: /platform-supplemental/drive-hotswap-sas.html
    - title: Switches
      url:  /other/switch-linkout.html
    - title: Cabinet and rail kits
      entries:
        - title: SuperRail kit
          url: /platform-supplemental/superrail-install.html
        - title: AFF A700/FAS9000 two-post rail kit
          url: /platform-supplemental/telco-installation-instructions.html
        - title: 42U 1280 mm system cabinet
          entries:
          - title: Prepare to install cabinet
            entries:
            - title: Cabinet features
              url: /platform-supplemental/42u-1280mm-features.html
            - title: Required tools/equipment
              url: /platform-supplemental/42u-1280mm-required-tools.html
            - title: Space requirements and cabinet dimensions
              url: /platform-supplemental/42u-1280mm-space-and-dimensions.html
            - title: Supported PDU types and specs
              url: /platform-supplemental/42u-1280mm-supported-pdu-types-and-specifications.html
          - title: Unpack system cabinet
            url: /platform-supplemental/42u-1280mm-unpack.html
          - title: Install cabinet
            entries:
            - title: Overview
              url: /platform-supplemental/42u-1280mm-install.html
            - title: Install cabinet interconnect kit
              url: /platform-supplemental/42u-1280mm-install-cabinet-interconnect-kit.html
            - title: Install bolt-down kit
              url: /platform-supplemental/42u-1280mm-install-bolt-down-kit.html
            - title: Install support rails
              url: /platform-supplemental/42u-1280mm-install-additional-rails.html
            - title: Install equipment
              url: /platform-supplemental/42u-1280mm-install-equipment.html
            - title: Power on cabinet
              url: /platform-supplemental/42u-1280mm-power-on.html
          - title: Replace PDUs
            url: /platform-supplemental/42u-1280mm-replace-pdus.html
          - title: Reverse cabinet front door
            entries:
            - title: What you need
              url: /platform-supplemental/42u-1280mm-reverse-front-door.html
            - title: Remove illuminated badge
              url: /platform-supplemental/42u-1280mm-remove-illuminated-badge.html
            - title: Remove cabinet door
              url: /platform-supplemental/42u-1280mm-remove-door.html
            - title: Move badge power supply and cabling
              url: /platform-supplemental/42u-1280mm-move-badge-ps-and-cabling.html
            - title: Reverse door hinge and lock catch
              url: /platform-supplemental/42u-1280mm-reverse-hinge-and-lock.html
            - title: Reinstall door and illuminated badge
              url: /platform-supplemental/42u-1280mm-reinstall-door-and-badge.html
    - title: Earlier models
      url: "/other/earlier-models.html"
    - title: Legal notices
      url: "/legal-notices.html"
