settings:
  search: ontap-systems
  name: "ONTAP Systems"
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: AFF and FAS system docs
      url: "/index.html"
    - title: Get started
      entries:
        - title: What's new
          url: /whats-new.html
        - title: Release notes
          url: /rel-notes.html
    - title: AFF systems
      entries:
      - section: c190
      - section: a200
      - section: a250
      - section: a300
      - section: a320
      - section: a400
      - section: a700s
      - section: a800
      - section: a900
    - title: FAS systems
      entries:
      - section: fas500f
      - section: fas2600
      - section: fas8200
      - section: fas8300
      - section: fas9500
    - title: AFF and FAS systems
      entries:
        - section: fas2700
        - section: fas9000
    - section: platform-supplemental
    - title: Drive shelves
      entries:
        - section: ns224
        - section: sas3
    - title: Earlier models
      url: "/other/earlier-models.html"
    - title: Legal notices
      url: "/legal-notices.html"
